@host = http://localhost:8001
@noteIdExample = vXRsEqLgBlgWlUaJs4Tp
@userId = 1

GET {{host}}/notes?userId={{userId}} HTTP/1.1

###

GET {{host}}/notes?userId={{userId}}&?id={{noteIdExample}} HTTP/1.1

###

POST {{host}}/notes HTTP/1.1
content-type: application/json

{
  "Name": "example",
	"Colour": "#FFFFFF",
	"Text": "example text",
  "UserId": "{{userId}}"
}

###

PUT {{host}}/notes?id={{noteIdExample}} HTTP/1.1
content-type: application/json

{
  "Name": "example update",
	"Colour": "#123456",
	"Text": "example text update",
  "UserId": "{{userId}}"
}

###

DELETE {{host}}/notes?id={{noteIdExample}} HTTP/1.1
